czo/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView

app_name = 'czo'

urlpatterns = [

    # Basic Things For User
    url(r'^$', login_required(views.index) , name='index'),
    url(r'^nodes/$', login_required(views.nodes) , name='nodes'),
    url(r'^data/$', login_required(views.data) , name='data'),
    url(r'^gateway/$', login_required(views.gateway) , name='gateway'),

    # test -- Will Remove after Completing Project
    url(r'^csv/$', login_required(views.csv_out) , name='test'),
    url(r'^otp/$', views.otp , name='otp'),
    url(r'^set_pass/$', views.set_pass , name='set_pass'),

    #for User To getting Permission for our website
    url(r'^login/$', views.login_user , name='login'),
    url(r'^logout/$', login_required(views.logout_user) , name='logout'),
    url(r'^register/$', views.Register_User.as_view() , name='register'),

    # For user
    url(r'^change_pass/$', login_required(views.change_pass) , name='change_pass'),
    url(r'^forget_pass/$', views.forget_pass , name='forget_pass'),
]

project1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from czo import views
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # For Admin
    url(r'^admin/', admin.site.urls),

    # for Root
    url(r'^$', views.kritsnam , name='kritsnam'),

    # For App
    url(r'^czo/', include('czo.urls' , namespace="czo")),

    # for overwriting login_required decorators
    url(r'^accounts/login/$', views.login_user , name='login'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

czo/models.py
from django.db import models
import datetime
from django.contrib.auth.models import Permission, User
from django.core.urlresolvers import reverse
from django.forms import ModelForm
import time
from django_unixdatetimefield import UnixDateTimeField

class Gateway(models.Model):

    device_id = models.CharField(max_length = 32, unique=True)
    name = models.CharField(max_length = 32)
    description = models.TextField(max_length = 196, blank=True)
    doc = models.DateTimeField(default=datetime.datetime.now)

    def get_absolute_url(self):
        return reverse('czo:index')

    def __str__(self):
        return self.name

# for Node --
class Node(models.Model):

    name = models.CharField(max_length = 32)
    gateway_name = models.ForeignKey(Gateway,on_delete = models.CASCADE)
    owner = models.ForeignKey(User,on_delete = models.CASCADE)
    description = models.TextField(blank=True)
    doc = models.DateTimeField(default=datetime.datetime.now)

    def get_absolute_url(self):
        return reverse('czo:index')

    def __str__(self):
        return self.name

class GatewayStats(models.Model):

    gateway = models.ForeignKey(Gateway,on_delete = models.CASCADE)
    free_memory = models.IntegerField(help_text="Free memory")
    vcell = models.FloatField(help_text="battery voltage")
    soc = models.FloatField(help_text="state of charge")
    rssi = models.IntegerField(help_text="rssi value")
    timestamp = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        ordering = ['-timestamp']

class NodeStats(models.Model):

    node = models.ForeignKey(Node, on_delete = models.CASCADE)
    data = models.FloatField()
    rssi = models.IntegerField(help_text="rssi value")
    battery = models.FloatField(help_text="battery voltage")
    timestamp = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        ordering = ['-timestamp']

    def get_absolute_url(self):
        return reverse('czo:index')

    def __str__(self):
        return str(self.data)

czo/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Node

# For overwriting Userfor for registering User.
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

czo/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from django.contrib.auth import authenticate,login, logout
from .forms import UserForm
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView,UpdateView, DeleteView
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render_to_response
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
import random, csv, datetime
from django.core.exceptions import ValidationError
import django.contrib.auth.password_validation as validators
from datetime import timedelta

def kritsnam(request):
    return render(request,'czo/kritsnam.html')

def gateway(request):
    if request.user.is_superuser == 1:
        gateway_id = request.GET.get('gateway_id')
        if gateway_id!=None:
            mygateway = Gateway.objects.filter(id=gateway_id)
            mygateways = Gateway.objects.all()
            if (mygateway):
                gatewaystats = GatewayStats.objects.filter(gateway=mygateway[0].id)[:10]
                print (len(gatewaystats))
                return render(request, 'czo/gateway.html' , { 'gateways' : mygateways, 'gatewaystats' : gatewaystats , 'gateway_id':int(gateway_id) })
            return render(request, 'czo/sensor.html')
        else:
            mygateways = Gateway.objects.all()
            if (mygateways):
                gatewaystats = GatewayStats.objects.filter(gateway=mygateways[0].id)[:10]
                return render(request, 'czo/gateway.html' , { 'gateways' : mygateways, 'gatewaystats' : gatewaystats , 'gateway_id':mygateways[0].id })
            return render(request, 'czo/sensor.html')
    else:
        return render(request,'500.html')

def change_pass(request):
    if request.method == "POST":
        curr_pass = request.POST['curr_pass']
        new_pass = request.POST['New_pass']
        if request.user.check_password(curr_pass):
            val = validators.validate_password(new_pass, request.user)
            print(val)
            if val is None:
                u = User.objects.get(username=request.user.username)
                u.set_password(new_pass)
                u.save()
                mynodes = Node.objects.filter(owner=request.user)
                return render (request,'czo/success1.html')
            else:
                return render(request,'czo/pass.html')
        else:
            return render(request,'czo/pass.html', {'error_message': 'Wrong Password'}  )
    else:
        return render(request,'czo/pass.html')

def set_pass(request):
    names = request.GET.get('username')
    if request.method == "POST":
        print('lol_post')
        otp = request.POST['otp']
        new_pass = request.POST['New_pass']
        u = User.objects.get(username=names)
        if u.first_name != '':
            if otp == u.first_name:
                u.set_password(new_pass)
                u.save()
                return render (request,'czo/success1.html')
        else:
            return render(request,'czo/set_pass.html', {'error_message': 'Wrong otp'}  )
    else:
        print('lol_get')
        return render(request, 'czo/set_pass.html' )

def forget_pass(request):
    if request.method == "POST":
        username = request.POST['username']
        user = User.objects.get(username=username)
        if user:
            subject =  "OTP for activation of your account: "
            x = random.randint(100000,999999)
            message =   ("Hi " + username + " Put this number in form to verify your Email : "
                        + str(x) + ", you can also follow to this link to set new_pass to your Account http://www.kritsnam.in/czo/set_pass/?username="
                        + username)
            to_email = user.email
            from_email = "satendrapandeymp@gmail.com"
            user.first_name = str(x)
            send_mail(subject, message, from_email, [to_email])
            user.save()
            return HttpResponseRedirect('/czo/set_pass/?username='+str(username))
        else:
            return render(request,'czo/forget_pass.html', {'error_message': 'Wrong username'}  )
    else:
        return render(request,'czo/forget_pass.html')

# It's for testing some new things
def otp(request):
        names = request.GET.get('username')
        print(names)
        myuser = User.objects.get(username=names)
        if request.method == "POST":
            otp = request.POST['otp']
            if len(myuser.last_name) < 5:
                if otp == myuser.first_name :
                    myuser.first_name=""
                    myuser.is_active = 1
                    myuser.save()
                    return render (request,'czo/success.html')
                else:
                    myuser.last_name = myuser.last_name + 'a';
                    print(myuser.last_name)
                    myuser.save()
                    return render(request, 'czo/login.html', {'error_message': 'Your account has been disabled'})
            else:
                subject =  "OTP for activation of your account: "
                x = random.randint(100000,999999)
                message =   ("Hi " + myuser.username + " Put this number in form to verify your Email : "
                            + str(x) + ", you can also follow to this link to verify your otp http://www.kritsnam.in/czo/otp/?username="
                            + myuser.username)
                to_email = myuser.email
                from_email = "satendrapandeymp@gmail.com"
                myuser.first_name = str(x)
                myuser.last_name = ""
                send_mail(subject, message, from_email, [to_email])
                user_name = str(myuser.username)
                myuser.save()
                return HttpResponseRedirect('/czo/otp/?username='+ str(user_name))
        return render(request,'czo/test.html' , {'names':names})

# it's for registering new user
class Register_User(View):
    form_class = UserForm
    template_name = 'czo/reg.html'

    def get(self,request):
        form = self.form_class(None)
        return render (request,self.template_name , {'form' :form })

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # normalised data_set
            username = form.cleaned_data ['username']
            password = form.cleaned_data ['password']
            val = validators.validate_password(password, username)
            if val is None:
                user.set_password(password)
                user.is_active = 0
                subject =  "OTP for activation of your account: "
                x = random.randint(100000,999999)
                message =   ("Hi " + username + " Put this number in form to verify your Email : "
                            + str(x) + ", you can also follow to this link to verify your otp http://www.kritsnam.in/czo/otp/?username="
                            + username)
                to_email = user.email
                from_email = "satendrapandeymp@gmail.com"
                user.first_name = str(x)
                send_mail(subject, message, from_email, [to_email])
                user_name = str(username)
                user.save()
                return HttpResponseRedirect('/czo/otp/?username='+ username)
            else:
                return render (request,self.template_name , {'form' :form })

# For user login
def login_user(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            return HttpResponseRedirect('/czo/')
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/czo/')
            else:
                return render(request, 'czo/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'czo/login.html', {'error_message': 'Invalid login'})
    else:
        if request.user.is_authenticated:
            return HttpResponseRedirect('/czo/')
        return render(request, 'czo/login.html')

# For logout user
def logout_user(request):
        logout(request)
        return HttpResponseRedirect('/')

# It's the homepage
def index(request):
        mynodes = Node.objects.filter(owner=request.user)
        return render(request, 'czo/index.html' , { 'mynodes' : mynodes})


# To find all Sensors att One place
def nodes(request):
    if request.method=="GET":
        node_id = request.GET.get('id')
        if node_id==None:
            mynodes = Node.objects.filter(owner=request.user)
            if (mynodes):
                timedelta1 = timedelta(days=7)
                datas = NodeStats.objects.filter(node=mynodes[0].id, timestamp__gte= datetime.datetime.now()-timedelta1)
                sensor_first = mynodes[0].id
                return render(request, 'czo/sensors.html' , { 'mynodes' : mynodes, 'datas' : datas , 'sensor_id' : sensor_first})
        else:
            var = 0
            mynodes = Node.objects.filter(owner=request.user)
            if (mynodes):
                mynode = Node.objects.filter(owner=request.user, id=node_id )[:1]
                if(mynode):
                    timedelta1 = timedelta(days=7)
                    datas = NodeStats.objects.filter(node=mynode[0].id, timestamp__gte= datetime.datetime.now()-timedelta1)
                    return render(request, 'czo/sensors.html' , { 'mynodes' : mynodes, 'datas' : datas , 'sensor_id' : int(node_id)})
    return render(request, 'czo/sensors.html')

# To find data of a sensor
def data(request):
    sensor_id = request.GET.get('node_id')

czo/templates/czo/AddUser.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

czo/templates/czo/base.html
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title  %} Kristnam {% endblock  %}</title>
    <script type="text/javascript" src="{% static '/js/jquery-1.11.3.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/bootstrap-theme.min.css' %}">
    <link rel="javascript" type="text/js" href= "{% static '/js/moment.js' %}">
    <link rel="javascript" type="text/js" href= "{% static '/js/style.js' %}">
    <link rel="stylesheet" type="text/css" href= "{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/fonts/font-awesome.min.css' %}">
  </head>

<body class="home">
    <div class="container-fluid display-table">
        <div class="row display-table-row">
            <div class="col-md-2 col-sm-2 hidden-xs display-table-cell v-align box" id="navigation">
                <div class="navi">
                    <ul>
                        <li class=""><a href="{% url 'czo:index' %}"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Home</span></a></li>
                        <li class=""><a href="{% url 'czo:nodes' %}"><i class="fa fa-tasks" aria-hidden="true"></i><span class="hidden.bs.tooltip">Nodes</span></a></li>
                        {% if request.user.is_superuser %}
                          <li class=""><a href="{% url 'czo:gateway' %}"><i class="fa fa-tasks" aria-hidden="true"></i><span class="hidden.bs.tooltip">Gateway</span></a></li>
                        {% endif %}
                   </ul>
                </div>
            </div>
            <div class="col-md-10 col-sm-11 display-table-cell v-align">
                <div class="row">
                    <header>
                        <div class="col-md-7">
                            <nav class="navbar-default pull-left">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                            </nav>
                        </div>
                        <div class="col-md-5">
                            <div class="header-rightside">
                                <ul class="list-inline header-top pull-right">

                                    <li class="dropdown">
                                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">

                                          <div id="user_set">
                                          <i class="fa fa-user" aria-hidden="true"></i>
                                          <strong> {{request.user}} </strong>
                                        </div>
                                        </a>

                                        <ul class="dropdown-menu">
                                            <li>
                                                <div class="navbar-content">
                                                    <a href="/" class="view btn-sm active" > <strong>kritsnam</strong></a>
                                                    <a href="{% url 'czo:change_pass' %}" class="view btn-sm active"> <strong>change_pass</strong></a>
                                                    <a href="{% url 'czo:logout' %}" class="view btn-sm active" > <strong>Logout</strong></a>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </header>
                </div>

                <div class="user-dashboard">
                    <div class="row">
                      {% block body_whole %}

                      {% endblock  %}

                        <div class="col-md-5 col-sm-5 col-xs-12 gutter">

                          {% block body %}

                          {% endblock  %}

                        </div>
                        <div class="col-md-7 col-sm-7 col-xs-12 gutter">

                          {% block body_right %}

                          {% endblock  %}

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</body>
</html>

czo/templates/czo/base_login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title  %}Login Page{% endblock  %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href= "{% static '/css/style.css' %}">
    <script src="{% static '/js/jquery-1.11.3.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static '/fonts/font-awesome.min.css' %}">
  </head>
  <style media="screen">
  body {
  background-color: #f4f6f6 ;
  }
  </style>
  <body>
      <div class="body_login">
        <nav class="navbar navbar-inverse ">
                  <div class="collapse navbar-collapse" id="#topNavbar">
                          <ul class="nav navbar-nav">
                                  <li class="">
                                        <a href="{% url 'czo:login' %}">
                                          <span class = "" area-hidden = "true" > </span> &nbsp; <b> Login </b>
                                        </a>
                                  </li>
                                  <li class="">
                                        <a href="{% url 'czo:register' %}">
                                          <span class = "" area-hidden = "true" > </span> &nbsp;<b> Register </b>
                                        </a>
                                  </li>
                                  <li class="">
                                        <a href="/">
                                          <span class = "" area-hidden = "true" > </span> &nbsp; <b> kritsnam </b>
                                        </a>
                                  </li>
                          </ul>
                  </div>
        </nav>

          {% block body  %}
          {% endblock  %}
        </div>
  </body>
</html>

czo/templates/czo/demo.html
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Kritsnam : Real-time data delivery Demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="mqttws31.js" type="text/javascript"></script>
    <script src="jquery.min.js" type="text/javascript"></script>
    <script src="config.js" type="text/javascript"></script>

    <script type="text/javascript">
    var mqtt;
    var reconnectTimeout = 3000;

    function MQTTconnect() {
	if (typeof path == "undefined") {
		path = '/mqtt';
	}
	mqtt = new Paho.MQTT.Client(
			host,
			port,
			path,
			"web_" + parseInt(Math.random() * 100, 10)
	);
        var options = {
            timeout: 3,
            useSSL: useTLS,
            cleanSession: cleansession,
            onSuccess: onConnect,
            onFailure: function (message) {
                $('#status').val("Connection failed: " + message.errorMessage + "Retrying");
                setTimeout(MQTTconnect, reconnectTimeout);
            }
        };

        mqtt.onConnectionLost = onConnectionLost;
        mqtt.onMessageArrived = onMessageArrived;

        if (username != null) {
            options.userName = username;
            options.password = password;
        }
        console.log("Host="+ host + ", port=" + port + ", path=" + path + " TLS = " + useTLS + " username=" + username + " password=" + password);
        mqtt.connect(options);
    }

    function onConnect() {
        $('#status').val('Connected to ' + host + ':' + port + path);
        // Connection succeeded; subscribe to our topic
        mqtt.subscribe(topic, {qos: 0});
        $('#topic').val(topic);
    }

    function onConnectionLost(response) {
        setTimeout(MQTTconnect, reconnectTimeout);
        $('#status').val("connection lost: " + responseObject.errorMessage + ". Reconnecting");

    };

    function freqPublish(){
	var node_id = document.getElementById('node_id').value;
	var topic = 'node/' + node_id + '/f';
	var frequency = document.getElementById('freq').value;
	var message = new Paho.MQTT.Message(frequency);

	message.destinationName = topic;
	message.qos = 1;
	
	mqtt.send(message);
    }    

    function onMessageArrived(message) {

        var topic = message.destinationName;
        var payload = message.payloadString;

	var table = document.getElementById("demo");
	var row = table.insertRow(1);
	var col0 = row.insertCell(0);
	var col1 = row.insertCell(1);
	var col2 = row.insertCell(2);
	var col3 = row.insertCell(3);
	var col4 = row.insertCell(4);


	var node_id = topic.split("/")[1]
	var msg = payload.split(",")
	col0.innerHTML = node_id;		// node_id
	col1.innerHTML = msg[0];		// data
	col2.innerHTML = msg[1];		// battery
	col3.innerHTML = msg[2];		// rssi

	var fTime = new Date(msg[3]*1000);
	var hours = fTime.getHours();
	var minutes = "0" + fTime.getMinutes();
	var seconds = "0" + fTime.getSeconds();
	var formattedTime = hours + ':' + minutes.substr(-2) + ':' + seconds.substr(-2);
	col4.innerHTML = formattedTime;		// timestamp
    };


    $(document).ready(function() {
        MQTTconnect();
    });

    </script>
  </head>
  <body>
    <h1>Real-Time data retrieval for Testing</h1>
    <div>
        <div>Subscribed to <input type='text' id='topic' disabled />
	Status: <input type='text' id='status' size="64" disabled /></div>

	<br /> 
	<br />
	<br />

	<div id="freqChange">
	<form action="#" onsubmit="freqPublish()" autocomplete="off">
	<table id="freqSubmit">
	<tr>
	<td><div>Node ID</div></td>
	<td><div><input type="text" id="node_id" value="3" disabled /></div></td>
	</tr>
	<tr>
	<td><div>Frequency</div></td>
	<td><div><input type="text" id="freq" value="" /></div></td>
	</tr>
	<td><div><input type="submit" value="Submit"/></div></td>
	</tr>
</table>
</form>
</div>
	<div id="demo_table">
	<table id="demo" cellspacing="32">
		<tr>
			<th>Node ID</th>
			<th>Data</th>
			<th>Battery</th>
			<th>RSSI</th>
			<th>Timestamp</th>
		</tr>
	</table>
	</div>
    </div>
  </body>
</html>

czo/templates/czo/login.html
{% extends "czo/base_login.html" %}

{% block title %}Log In{% endblock %}

{% block body %}

<div class="login_field">

<div class="centered">

<div class="container">

    <div class="row">
        <div class="col-sm-12 col-md-6">

                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'czo:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-14">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                    <div id="forget">
                      <a href="{% url 'czo:forget_pass' %}">Forgot Password?</a>
                    </div>
            </div>
        </div>
    </div>

</div>

</div>

</div>

{% endblock %}

czo/templates/czo/reg.html
{% extends "czo/base_login.html" %}

{% block title  %} Create Account {% endblock  %}

{% block body  %}



<div class="reg_field">

<div class="centered">

<div class="container">

    <div class="row">
        <div class="col-sm-12 col-md-6">

                <div class="panel-body">
                    <strong> <h4> Register:</h4> </strong>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'czo:register'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text" placeholder="Your username">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password" placeholder="Atleast 8 char and num long">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_email">
                                Email:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_email" maxlength="30" name="email" type="email" placeholder="Your Valid email id for otp">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-15">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

            </div>
        </div>
    </div>

</div>

</div>

</div>

{% endblock  %}

czo/templates/czo/sensor_confirm_delete.html
{% extends "czo/base.html" %}

{% block title %}Home{% endblock %}

{% block body %}

<div class="" id="Left_Side">
  <form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ object }}"?</p>
      <input type="submit" value="Confirm" />
      <input type="submit" value="Cancel" onClick="javascript:history.go(-1);" />
  </form>
</div>




{% endblock %}

{% block body_right %}

<div class="" id="Right_Side">

  <h3> Here are something that can help you </h3>
    <p>
        We made a help page to help you throughout.
        We will gonna put some suggestion for you here.
    </p>
</div>




{% endblock body_right %}

czo/templates/czo/success1.html
{% extends "czo/base_login.html" %}

{% block title %}Log In{% endblock %}

{% block body %}

<div id="login">

<div id="register">

<div class="container-fluid">

  <h3> Your password is changed successfully, Now login again to continue. <br> <br>

  </h3>
  <p>
    <a href="/czo/login"> Click  </a> here to login.

  </p>
</div>

</div>

</div>

{% endblock %}